# Generated by Django 4.2.3 on 2024-05-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeepney_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeepney',
            name='destination_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jeepney',
            name='origin_code',
            field=models.IntegerField(),
        ),
    ]
