# Generated by Django 4.2.3 on 2024-05-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeepney_api', '0002_alter_jeepney_destination_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeepney',
            name='jeepney_service_no',
            field=models.IntegerField(),
        ),
    ]
