# Generated by Django 4.2.3 on 2024-05-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeepney_api', '0004_passengervolume'),
    ]

    operations = [
        migrations.CreateModel(
            name='JeepneyStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeepney_stop_code', models.CharField(max_length=20, unique=True)),
                ('road_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
