# Generated by Django 4.2.3 on 2024-05-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeepney_api', '0005_jeepneystop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengervolume',
            old_name='volume_of_passengers',
            new_name='passenger_volume',
        ),
    ]
