# Generated by Django 4.2.3 on 2024-05-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeepney_api', '0006_rename_volume_of_passengers_passengervolume_passenger_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengervolume',
            name='passenger_volume',
            field=models.CharField(max_length=20),
        ),
    ]
